import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { allHosiery } from "@/lib/data";
import { HosieryCard } from "@/components/HosieryCard";
import { learnArticles } from "@/lib/learnArticles";

const titles: Record<string, [string, string]> = { denier: ["Denier and transparency", "Denier is a fiber-density reference; color, knit and light change how transparent a pair reads."], "20d-vs-40d": ["20D vs 40D", "Compare a sheer reference and a denser reference under the same light."], "copy-hosiery-vs-full-prompt": ["Copy hosiery vs full prompt", "Choose the reusable material paragraph or the complete tested scene."], "length-guide": ["Length and structure", "Thigh-highs, stockings and pantyhose differ at the upper edge and in how the garment connects."], glossary: ["Hosiery glossary", "The terms that make a hosiery prompt precise."], finish: ["Finish", "Matte, natural, satin and gloss change how a surface catches the same light."], "black-sheer-slimming": ["Why sheer black reads as contoured", "A visual explanation of gradients, contrast and surface."], "first-prompt": ["Your first hosiery prompt", "A practical starting point for assembling a character and hosiery reference."] };

export const metadata = { title: "Hosiery 101 · HosieryLab", description: "Learn how denier, transparency, length, color and finish change a hosiery reference.", alternates: { canonical: "/en/learn" } };
export default function EnglishLearnPage() { const samples = allHosiery.filter((item) => item.denier !== null).slice(3, 6); return <><SiteHeader locale="en" /><main className="shell article-page"><div className="article-hero"><p className="eyebrow">HOSIERY 101</p><h1>Understand the variable,<br /><em>then choose.</em></h1><p>Break common hosiery terms into observable variables, then return to the catalog to find a record you can inspect and copy.</p></div><div className="article-index-list">{learnArticles.map((article, index) => { const [title, summary] = titles[article.slug] ?? [article.title, article.summary]; return <Link className="article-index-row" href={`/en/learn/${article.slug}`} key={article.slug}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{summary}</p></div><b>Read →</b></Link>; })}</div><section className="article-samples"><div className="section-heading"><div><div className="section-kicker">TRY A REAL RECORD</div><h2>Put the variables together.</h2></div><Link className="quiet-link" href="/en/hosiery">Explore more →</Link></div><div className="featured-grid">{samples.map((item) => <HosieryCard item={item} key={item.code} locale="en" />)}</div></section></main></> }
