import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/SiteHeader";
import { learnArticles, getLearnArticle } from "@/lib/learnArticles";
import { MarkdownArticle } from "@/components/MarkdownArticle";

const EnglishArticleText: Record<string, string> = {
  denier: "## The short version\n\nDenier (D) is the weight of a yarn, not a transparency percentage. Higher numbers usually produce a denser knit, but color, knit, stretch and light still change what the eye sees.\n\nUp to 10D reads as ultra sheer; 11–20D as sheer; 21–35D as semi-sheer; 36–59D as semi-opaque; 60–99D as opaque; and 100D or more as heavy opaque. Fishnet and lace are open structures, so a denier range is not the useful variable.\n\nIn a prompt, keep the number together with a visual description such as ‘skin remains visible through the front of the calf, with deeper edges.’",
  "20d-vs-40d": "## One sentence\n\n20D usually reads as a visible layer over the leg. 40D reads more like a complete color with only a little skin showing. On black hosiery, the difference is clearest at the front of the calf, the knee, the instep and the side edges.\n\nWhen writing a prompt, change both the D number and the transparency sentence. Changing only ‘20D’ to ‘40D’ often leaves the image model with the old visual instruction.",
  "copy-hosiery-vs-full-prompt": "## Two different jobs\n\nCopy hosiery gives you color, denier, opacity, finish, knit, motif and top-edge details. Copy full prompt preserves the complete reference: person, clothing, camera, setting, lighting and hosiery.\n\nWrite your character and clothing first, then the action and camera, then paste the hosiery paragraph. Remove an older hosiery description before pasting a new one, or the model may mix them. The hosiery paragraph is portable, but it is not separately tested in every character or tool.",
  "length-guide": "## Use the upper edge\n\nA footie ends below the ankle. Ankle, crew and mid-calf socks stop progressively higher. Knee-highs finish below the knee, over-the-knee socks finish above it, and thigh-highs reach the middle or top of the thigh. Pantyhose and tights continue to the waist.\n\nStockings use suspenders, stay-ups use an internal grip, and over-the-knee socks rely on the top band. Check the image and the length filter together because these words are mixed in everyday use.",
  glossary: "## Small terms matter\n\nA welt is the reinforced upper edge. A lace top adds a lace band. A silicone grip lets a stay-up hold without suspenders. A back seam runs up the rear centre of the leg; a mock seam is knitted or printed into a modern tube.\n\nA Cuban heel is a square reinforced heel and a French heel narrows to a point. A reinforced toe is denser, while a sheer toe keeps the toe as transparent as the leg. Say ‘reinforcement knitted into the hosiery’ so a model does not interpret a heel term as a shoe style.",
  finish: "## Finish is the highlight\n\nMatte has almost no distinct highlight. Semi-matte is broad and quiet. Satin is soft and continuous. Glossy is clearer, high-shine is brighter, wet-look reflects across most of the leg, and shimmer creates small points rather than one band.\n\nFinish is separate from denier. Wet-look needs ‘visible knit remains, not latex’; satin needs a soft fading edge; shimmer needs fine metallic thread woven into the fabric, not sequins.",
  "black-sheer-slimming": "## The visual effect\n\nA leg is approximately cylindrical. At the front, the viewer looks through a shorter path of knit and sees more skin. At the sides, the viewing angle crosses more layers, so the hosiery looks darker. Stretch at the knee and front of the calf adds another change.\n\nThe effect is usually strongest around 15–40D. In a prompt, keep the instruction ‘front of the calf and knee are more transparent, with the sides gradually deepening.’ Without it, a model may produce a flat black block.",
  "first-prompt": "## Start simple\n\nA useful first reference is black, 20–40D, pantyhose, matte or semi-matte, with no motif. Copy the full prompt and run it unchanged once. Check that the calf front is more transparent than the sides, both legs match, the upper edge is correct, the feet remain covered, and the surface reads as knit rather than latex or paint.\n\nAfter that, copy only the hosiery paragraph into your own character prompt. Change one variable at a time: denier, then finish, then length."
};

export function generateStaticParams() { return learnArticles.map((article) => ({ slug: article.slug })); }
export default async function EnglishArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = getLearnArticle(slug); if (!article) notFound(); return <><SiteHeader locale="en" /><main className="shell article-page"><Link className="back-link" href="/en/learn">← Back to Hosiery 101</Link><div className="article-hero"><p className="eyebrow">HOSIERY 101</p><h1>{article.title}</h1><p>{article.summary}</p></div><article className="article-body"><MarkdownArticle body={EnglishArticleText[slug] ?? "This article is being prepared."} /></article><Link className="text-link" href="/en/hosiery">Browse the catalog →</Link></main></> }
