window.HL_DATA = [
  {
    "den": 15,
    "hex": "#171719",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "ultra_sheer",
    "color": "纯黑",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000001"
  },
  {
    "den": 40,
    "hex": "#a8755d",
    "fin_code": "Matte",
    "bucket": "waist",
    "texture": "Ribbed",
    "opacity": "opaque",
    "color": "酒红",
    "cat": "连裤袜",
    "finish": "Matte",
    "code": "HL-A000002"
  },
  {
    "den": 20,
    "hex": "#171719",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "纯黑",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000003"
  },
  {
    "den": 12,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "蜜裸",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000004"
  },
  {
    "den": 10,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "ultra_sheer",
    "color": "蜜裸",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000005"
  },
  {
    "den": 40,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "咖啡棕",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000006"
  },
  {
    "den": 30,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "海军蓝",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000007"
  },
  {
    "den": 20,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Seamed",
    "opacity": "sheer",
    "color": "炭灰",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000008"
  },
  {
    "den": 30,
    "hex": "#a8755d",
    "fin_code": "Matte",
    "bucket": "waist",
    "texture": "Ribbed",
    "opacity": "sheer",
    "color": "酒红",
    "cat": "连裤袜",
    "finish": "Matte",
    "code": "HL-A000009"
  },
  {
    "den": 15,
    "hex": "#a8755d",
    "fin_code": "Satin",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "炭灰",
    "cat": "连裤袜",
    "finish": "Satin",
    "code": "HL-A000010"
  },
  {
    "den": 15,
    "hex": "#171719",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "ultra_sheer",
    "color": "纯黑",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-A000011"
  },
  {
    "den": 40,
    "hex": "#a8755d",
    "fin_code": "Matte",
    "bucket": "waist",
    "texture": "Plain",
    "opacity": "opaque",
    "color": "纯白",
    "cat": "连裤袜",
    "finish": "Matte",
    "code": "HL-A000012"
  },
  {
    "den": 10,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "纯白",
    "cat": "吊带袜",
    "finish": "Natural",
    "code": "HL-B000001"
  },
  {
    "den": 10,
    "hex": "#a8755d",
    "fin_code": "Satin",
    "bucket": "waist",
    "texture": "Seamed",
    "opacity": "ultra_sheer",
    "color": "炭灰",
    "cat": "连裤袜",
    "finish": "Satin",
    "code": "HL-B000002"
  },
  {
    "den": 20,
    "hex": "#171719",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Seamed",
    "opacity": "sheer",
    "color": "纯黑",
    "cat": "连裤袜",
    "finish": "Natural",
    "code": "HL-B000003"
  },
  {
    "den": 25,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Plain",
    "opacity": "ultra_sheer",
    "color": "炭灰",
    "cat": "吊带袜",
    "finish": "Natural",
    "code": "HL-B000004"
  },
  {
    "den": 8,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "炭灰",
    "cat": "大腿袜",
    "finish": "Natural",
    "code": "HL-B000005"
  },
  {
    "den": 5,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Seamed",
    "opacity": "sheer",
    "color": "自然肤色",
    "cat": "大腿袜",
    "finish": "Natural",
    "code": "HL-B000006"
  },
  {
    "den": 5,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Plain",
    "opacity": "ultra_sheer",
    "color": "自然肤色",
    "cat": "吊带袜",
    "finish": "Natural",
    "code": "HL-B000007"
  },
  {
    "den": 15,
    "hex": "#171719",
    "fin_code": "Natural",
    "bucket": "waist",
    "texture": "Mesh",
    "opacity": "sheer",
    "color": "纯黑",
    "cat": "网袜",
    "finish": "Natural",
    "code": "HL-B000008"
  },
  {
    "den": 15,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Plain",
    "opacity": "ultra_sheer",
    "color": "纯白",
    "cat": "吊带袜",
    "finish": "Natural",
    "code": "HL-B000009"
  },
  {
    "den": 20,
    "hex": "#a8755d",
    "fin_code": "Satin",
    "bucket": "thigh_high",
    "texture": "Seamed",
    "opacity": "sheer",
    "color": "自然肤色",
    "cat": "大腿袜",
    "finish": "Satin",
    "code": "HL-B000010"
  },
  {
    "den": 30,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Seamed",
    "opacity": "sheer",
    "color": "纯白",
    "cat": "大腿袜",
    "finish": "Natural",
    "code": "HL-B000011"
  },
  {
    "den": 15,
    "hex": "#a8755d",
    "fin_code": "Natural",
    "bucket": "thigh_high",
    "texture": "Plain",
    "opacity": "sheer",
    "color": "炭灰",
    "cat": "大腿袜",
    "finish": "Natural",
    "code": "HL-B000012"
  }
];
