import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { HeroExperiment } from "@/components/HeroExperiment";
import { HosieryCard } from "@/components/HosieryCard";
import { allHosiery } from "@/lib/data";

export const metadata = { title: "HosieryLab — Every pair, under the same light.", description: "A visual hosiery reference for designers, stylists and AI character creators.", alternates: { canonical: "/en" } };

export default function EnglishHome() {
  return <><SiteHeader locale="en" /><main><section className="hero shell"><div className="hero-copy"><p className="eyebrow">THE VISUAL INTELLIGENCE INDEX FOR HOSIERY</p><h1>Every pair,<br /><em>under the same light.</em></h1><p className="hero-lede">A measured visual index organized by length, coverage, denier, color, material, finish and structure.</p><p className="hero-audience">Built for designers, stylists and AI character creators who need hosiery to look right.</p><div className="hero-actions"><Link className="button button-dark" href="/en/hosiery">Explore the catalog <span>↗</span></Link><Link className="quiet-link" href="/en/about/sources">Read our method</Link></div></div><HeroExperiment locale="en" /></section><section className="quick-section shell"><div className="section-kicker">START WITH A QUESTION</div><div className="quick-filters">{[["Black", "color=black"], ["Skin tones", "color=skin_tone"], ["≤10D", "denier=0-10"], ["11–20D", "denier=11-20"], ["40D+", "denier=40-999"], ["Sheer", "opacity=sheer"], ["Matte", "q=matte"], ["Pattern", "q=pattern"]].map(([label, query]) => <Link key={label} href={`/en/hosiery?${query}`} className="quick-pill">{label}</Link>)}</div></section><section className="featured-section shell"><div className="section-heading"><div><div className="section-kicker">FEATURED REFERENCES</div><h2>One variable at a time.</h2></div><Link className="quiet-link" href="/en/hosiery">View all specimens →</Link></div><div className="featured-grid">{allHosiery.slice(0, 3).map((item) => <HosieryCard item={item} key={item.code} locale="en" />)}</div></section><section className="method-band"><div className="shell method-inner"><div><div className="section-kicker">OUR METHOD</div><h2>Facts first.<br /><em>Visuals with a source.</em></h2></div><div className="method-copy"><p>Every record keeps its image, prompt layers and metadata together, with provenance for fair comparison.</p><Link className="button button-light" href="/en/about/sources">How the lab works <span>↗</span></Link></div></div></section></main></>;
}
